# Generated by Django 6.0.5 on 2026-05-07 21:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('internships', '0002_alter_internshipoffer_internship_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptee'), ('rejected', 'Rejetee')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('student', 'offer'), name='unique_student_offer_application'),
        ),
    ]
