# Generated by Django 6.0.3 on 2026-05-07 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('domain', models.CharField(max_length=100)),
                ('required_skills', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('internship_type', models.CharField(choices=[('presentiel', 'Présentiel'), ('remote', 'À distance'), ('hybride', 'Hybride')], max_length=20)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('closed', 'Fermée')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
