# Generated by Django 6.0.5 on 2026-05-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipoffer',
            name='internship_type',
            field=models.CharField(choices=[('presentiel', 'Presentiel'), ('remote', 'Remote'), ('hybride', 'Hybride')], max_length=20),
        ),
        migrations.AlterField(
            model_name='internshipoffer',
            name='status',
            field=models.CharField(choices=[('open', 'Ouverte'), ('closed', 'Fermee')], default='open', max_length=20),
        ),
    ]
