# Generated by Django 6.0.3 on 2026-05-07 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Étudiant'), ('company', 'Entreprise')], max_length=20)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('field', models.CharField(blank=True, max_length=100)),
                ('study_level', models.CharField(blank=True, max_length=100)),
                ('skills', models.TextField(blank=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
