# Generated by Django 6.0.5 on 2026-05-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Etudiant'), ('company', 'Entreprise')], max_length=20),
        ),
    ]
